spring:
  application:
    name: organization

  datasource:
    url: jdbc:postgresql://localhost:5434/organization_db
    username: postgres
    password: password

  jpa:
    hibernate:
      ddl-auto: update

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:18080/realms/bff-task
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

server:
  port: 8082

jwt:
  auth:
    converter:
      resource-id: organization-service
      principal-attribute: principal_username

logging:
  level:
    org:
      springframework:
        security: DEBUG
