spring:
  application:
    name: organization

  datasource:
    url: jdbc:postgresql://localhost:5434/organization_db
    username: postgres
    password: password

  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8082
